### ISSUE TITLE
Typo with topBar.scss

### ISSUE THREAD

**Issue by sven-herrmann** [mtgatool/mtgatool-desktop#1]
file is named TopBar.scss, but code refers to it with topBar.scss

**Comment by Manuel-777** [comment]
Weird, github does not pick up the file name change when I push it in lowercase
![image](https://user-images.githubusercontent.com/4711391/133708714-6a942de9-c900-4af8-a2bf-6f9d60140191.png)

**Comment by sven-herrmann** [comment]
Weird you are probably working on windows, where files names are not case-sensitive.
Thus git won't even know the filename changed.
Created #2 for you :)

**Comment by Manuel-777** [comment]
Yeah, indeed im on Windows, thank you !
