### ISSUE TITLE
Can't create an account

### ISSUE THREAD

**Issue by progressquest** [mtgatool/mtgatool-desktop#10]
When trying to sign up, I get: 
Mixed Content: The page at 'https://mtgatool.com/register' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://api.mtgatool.com:8765/gun'. This request has been blocked; this endpoint must be available over WSS.

**Comment by CoderChang65535** [comment]
Similar issue, but I see an error
![image](https://user-images.githubusercontent.com/19420270/140373392-84a3d8ed-effb-4691-9f2d-13e4d0a3bd36.png)

**Comment by Manuel-777** [comment]
Already updated the website (removed the dead pages), so im closing this issue.

Thanks!
