### ISSUE TITLE
Clicking the back button causes "Minified React error #130"

### ISSUE THREAD

**Issue by artillect** [mtgatool/mtgatool-desktop#12]
Steps to reproduce:

1. Open the "My Decks" tab or "History" tab and click on a deck or game to view it
2. Click on the back button in the top left, and the game crashes.

This appears to happen when clicking on any of the back buttons

Here's a screenshot of the error message that pops up:
![image](https://user-images.githubusercontent.com/8906201/143976165-499134b7-87e8-402e-a470-7f9739c2bd4f.png)

And some screenshots of the more detailed error log:
![image](https://user-images.githubusercontent.com/8906201/143976247-5c34c785-352e-45ea-bc7e-475dc6955403.png)

![image](https://user-images.githubusercontent.com/8906201/143976285-2dd2061e-7a66-4406-aca5-716920ee1f94.png)

**Comment by riQQ** [comment]
Works for me in 6.1.26. Can you confirm?

**Comment by guru-of-sound** [comment]
> Works for me in 6.1.26. Can you confirm?
Doesnt work for me. Still get this error when backing out of decklist view
![image](https://user-images.githubusercontent.com/1421548/152423409-7937616a-d7ca-4ef9-af17-dab329da901c.png)

**Comment by sonicfly** [comment]
I got the same issue.

**Comment by riQQ** [comment]
Likely fixed with 6.1.28 / ffa62e393f7d79580e4585adb7019220a1e32e1a. Can you confirm?

**Comment by artillect** [comment]
@riQQ Yup, it works!
