### ISSUE TITLE
 TypeError when accessing Collection tab

### ISSUE THREAD

**Issue by arfar** [mtgatool/mtgatool-desktop#13]
Hi there

Whenever I try to use the "Collection" tab, I get the following error:

TypeError: Cannot read property "inventory" of undefined

I'm really not sure what further to put unfortunately as the logs provided to not really say much other than the error started from main.1f89d86d.chunk.js:1:1610372.

It has worked once or maybe twice since installing it a few days ago, but most of the time it does not.

I'm running on Linux, PopOs 21.04 running "mtgatool-desktop-6.1.21.AppImage"

I attach a screenshots
![Screenshot from 2021-12-16 23-00-13](https://user-images.githubusercontent.com/2935358/146597161-e659838b-d898-45d4-93fb-c08090416d35.png)
![Screenshot from 2021-12-16 23-02-18](https://user-images.githubusercontent.com/2935358/146597165-ca535376-6d94-4ba8-9f99-150543c369c1.png)

Once this error is encountered, nothing in the app can be used (effectively just locked up and I have to kill it).

Very happy to try any further steps to troubleshoot/diagnose. I understand this is a bit of a useless bug report in its current form.

Thanks in advance
Arthur

**Comment by Manuel-777** [comment]
This one should be fixed in the next release, thanks for reporting!

**Comment by riQQ** [comment]
Collection tab works for me and there have been a few releases. This should be fixed.
