### ISSUE TITLE
Deleted statistics partially return

### ISSUE THREAD

**Issue by Dunkhan** [mtgatool/mtgatool-desktop#15]
I deleted my db once reaching diamond because the deck stats are no longer valid. A deck's win rate in the lower tiers is no indication of performance against harder decks. After a few days about half of the decks suddenly changed to having vastly more games played than were actually played. The stats appear to be previous actual games from before I deleted the db. I deleted the whole Arena Tool folder because I am not sure what files need to be deleted for this (on Linux).

In addition to this bug, it would be nice to be able to reset the deck win stats without deleting all the data.

**Comment by Manwe-777** [comment]
This is an old issue but still requires an explanation!

What happened here was that the data stayed in remote peers and when you signed in again, the data war retrieved again. There is no delete option anymore since all data is synchronized and shared between peers.

Since the issue was first opened I added an archive option to decks that might suit this use case, although I reckon it might not be enough to clear a deck's history and start over, to do that you might be better off creating a new/different deck in MTGA thats a copy of the orignal one.

**Comment by Dunkhan** [comment]
On second thoughts, I have a lot of decks and this is a major hassle. Any scope for a feature request that makes this easier?

**Comment by Dunkhan** [comment]
Ok this doesn't work at all. I am unable to archive decks and when I clone a deck and delete the original, then rename it back, half the time the stats get added to the old deck anyway. Can this be reopened as there is currently no workable way to reset deck stats?

**Comment by Manwe-777** [comment]
Of couse, can you reproduce it consistently though? Just to be sure I can identify where the problem actually is, bear in mind a couple things;
- Renaming/editing a deck in MTGA does not create a new entry for that deck. Decks have an ID that is created by MTGA.
- On mtgatool you can archive by clicking the eye icon on any deck to hide it.
- It might just be a networking issue! if your archived decks come back as un-archived tool might not be persisting the new archived decks list properly on the server ? you can test this using both the desktop app and web to check the sync [(https://app.mtgatool.com/)](https://app.mtgatool.com/)

**Comment by Dunkhan** [comment]
Reproduction: remake decks - 
1. Take an account with several decks that already have games played in the mtgatool stats
2. Clone multiple decks (my test was with 12)
3. Delete all the original decks
4. Remove the (1) at the end of each cloned deck name to get the original names back
5. play a game with each deck
6. observe the statistics in the application - the additional game is added to the total for the old deck
In my first test 3 of the 12 decks showed only 1 game played,  or added to the previous totals

While writing this I discovered something:
7. Edit one of the decks that is not updating correctly, changing at least one card
8. Play a game with the deck
9. observe the statistics in the application - the deck now displays 2 games and is separate from the old deck, this includes the game played in step 5

With regard to the archiving, there appears to be an index error. Let me know if you wish me to make a separate report for this:
1. Go to the deck list
2. Click the eye icon to archive a deck (A) - the deck (A) is removed
3. Click the eye icon in the deck (B) that now shows in the position the deck in step 2 was in
4. Observe that the deck (A) is now shown on the deck list again. Deck (B) is hidden

Steps 2-4 can be repeated alternating between deck (A) and (B)
There may be a sequence that allows all decks to be hidden but it is hard to discover.

I hope this is useful, and I appreciate all the work you do.
