### ISSUE TITLE
Unexpected Card Type : Dungeon

### ISSUE THREAD

**Issue by Legendofpie** [mtgatool/mtgatool-desktop#18]
I have been playing against players that make use of the Dungeons and Dragons card set. There is card types that have the name Dungeon. This causes the app to throw an error popup(see attached). There is no way to dismiss this popup. Restarting the app will just show the popup again. 

Im running the AppImage version of this with the mtga daemon tool as per the instructions on the readme. 

Pop OS 21.10

![image](https://user-images.githubusercontent.com/14097594/147980934-faccd1da-82c9-497e-b0aa-cac615b719cf.png)

**Comment by Manwe-777** [comment]
Closing since this should be fixed in a previous update, but please feel free to re open or tag me if its not !
