### ISSUE TITLE
Can't sign up

### ISSUE THREAD

**Issue by fe-sak** [mtgatool/mtgatool-desktop#19]
I'm probably signing up wrong, but any username I submit on the signup page it returns an error "Could not find user". I tried using the same username as arena, tried a totally different one and also tried an email...

**Comment by riQQ** [comment]
Please open the Developer Tools by pressing <kbd>alt</kbd> + <kbd>shift</kbd> + <kbd>d</kbd>, check for the detailed error there, and post it here.

**Comment by Manwe-777** [comment]
Also, please check if you are properly connected to the API/peers (in desktop you have the settings to check this in the bottom left)

**Comment by fe-sak** [comment]
> Also, please check if you are properly connected to the API/peers (in desktop you have the settings to check this in the bottom left)
Looks like I'm connected to the API and one peer, but there is one which I can't connect.
Alos, here's my log: `
electron/js2c/renderer_init.js:13 (electron) The remote module is deprecated. Use https://github.com/electron/remote instead.
log @ electron/js2c/renderer_init.js:13
database-wrapper.ts:70 Loaded metadata from cache (/home/fesak/.config/mtgatool-desktop/database.json)
App.tsx:76 Merged Peers:  Array(1)0: {host: "api.mtgatool.com", port: 443}length: 1__proto__: Array(0)
App.tsx:95 Can log in? true
tmp/.mount_mtgato7bjtqr/resources/app.asar/build/:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
mtgaTrackerDaemon.ts:71 mtgaTrackerDaemon downloadLatestDaemon
mtgaTrackerDaemon.ts:101 mtgaTrackerDaemon update? 1.0.5.0 0.0.0.0
mainChannelListeners.ts:51 Peers:  Array(2)
mainChannelListeners.ts:51 Peers:  Array(3)
mainChannelListeners.ts:51 Peers:  Array(3)
database-wrapper.ts:87 Updated cards database OK
database-wrapper.ts:88 New DB version:  136
database-wrapper.ts:48 Saved metadata to /home/fesak/.config/mtgatool-desktop/database.json
mtgaTrackerDaemon.ts:255 mtgaTrackerDaemon getStatus()
mtgaTrackerDaemon.ts:202 mtgaTrackerDaemon shutdown()
`

**Comment by fe-sak** [comment]
Well, never mind! It worked!

**Comment by fe-sak** [comment]
Now I must find where my logs are. I installed through lutris and then through epic store

**Comment by Manwe-777** [comment]
Excellent! Please leave this issue open anyway since it is a recurring issue in the current release

**Comment by fe-sak** [comment]
Understood! Thank you for your attention.  You guys rock!


Just an FYI for anyone who also installed through the Epic Store. This is the path to your Player.log:

`/home/YOUR-USER-NAME/Games/epic-games-store/drive_c/users/YOUR-USER-NAME/AppData/LocalLow/Wizards Of The Coast/MTGA/Player.log`
