### ISSUE TITLE
Action logs only show beginning turns

### ISSUE THREAD

**Issue by zyll71** [mtgatool/mtgatool-desktop#21]
Action logs for previously played games (accessed via History) only show turns beginning, players conceeding, winning and loosing.
I am pretty certain that previously more information was shown (e.g. triggered abilities, spells cast, etc.).

Action logs from games played "about a month ago" do not show additional info either. Therefore, I think it is safe to assume that at least the NEO update of Arena is not responsable for breaking this. However, this still might be due to a different, previous update ("earlier than about a month ago") of Arena.

Of course, the loss of detailed action logs might have been introduced in recent updates of the mtgatool-desktop client.

I see this behaviour is on both Linux and Windows versions of the mtgatool-desktop client.

**Comment by Manwe-777** [comment]
I am aware of this one! Aparently some parts of the log parser need a little update

**Comment by Manwe-777** [comment]
Fixed at 149ba4dc327c98bb50460caa385770ed5f9f0702
