### ISSUE TITLE
I'm getting an error that reads "TypeError: Cannot read property 'forEach' of null" when trying to access the History tab.

### ISSUE THREAD

**Issue by Manyfans** [mtgatool/mtgatool-desktop#24]
I don't know why this could be happening. I tried restarting MTG Arena Tool, restarting Arena, and uninstalling and reinstalling MTG Arena Tool. I wasn't able to find any help on Google, so I figured that I'd post the error myself.

![MTG Arena Tool Error](https://user-images.githubusercontent.com/38590329/166106363-c2a1b47b-7264-4bef-bd9a-d71204b9db8b.png)

So, this screen pops up when I click on the History tab, _however_ the other tabs **are still clickable**—they're just not visible. I hope there's something that can be done.

**Comment by riQQ** [comment]
Works for me, so it's something particular in your history data that is causing this.

**Comment by Manwe-777** [comment]
Yep, that seems to be the case, ill check if theres something ovbious but the error coes not specify which component it is
