### ISSUE TITLE
What happened to this app?

### ISSUE THREAD

**Issue by max1c** [mtgatool/mtgatool-desktop#27]
MTGATool used to be my favorite MTGA tracker tool. It wasn't perfect but it had all kinds of useful features and beautiful interface. How come all of the features are gone and whatever is there now barely works?

**Comment by Manwe-777** [comment]
Hi there!

Its still alive, and we still have most of the features we had! Its been definitely stalled recently (too much work and no time for open source as much!) but the idea is to catch up with v5 features at some point, and improve them if possible.
