### ISSUE TITLE
Explore data aggregator doesn't show Mid Week Magic events

### ISSUE THREAD

**Issue by riQQ** [mtgatool/mtgatool-desktop#35]
This has been happening for a long time, but it was working at some point in version 6.x as far as I remember.

Confirmed broken in version 6.1.36

**Comment by Manwe-777** [comment]
Yeah I been triying to solve this automatically but WoTC removed the events list once again, might have to keep a manual list updated or find a different source for the current/active events and relay it trough all peers

**Comment by riQQ** [comment]
What about populating the events from recorded games?

**Comment by riQQ** [comment]
Related commit: https://github.com/mtgatool/mtgatool-desktop/commit/e29a8e5ca50dc37e7973b4f26cb257369da6d68d
Midweek Magic event this week was still not shown in the explore data aggregator.

**Comment by riQQ** [comment]
Successfully tested with 6.1.39 of the desktop app and 6.1.38 of the web app.
