### ISSUE TITLE
Deck list sorting constantly resets

### ISSUE THREAD

**Issue by Dunkhan** [mtgatool/mtgatool-desktop#36]
Reproduction:
Open the deck view
Sort it by win rate (or anything not the default)
wait a moment
Note that the ordering of the list resets randomly.

I am reporting this to document it as I fix it. This should be resolved soon.

**Comment by Manwe-777** [comment]
The reset happens because data is refreshed by the network causing the list component to re-render (delayed updates or just having mutiple peers connected, etc), so the PR fix is actually very good!
