### ISSUE TITLE
With a large amount of unique cards it would be great if the tracker could be more than one column

### ISSUE THREAD

**Issue by maxinfet** [mtgatool/mtgatool-desktop#42]
I would like to be able to make the deck tracker overlay multiple columns so that I can see my entire deck on a vertical monitor ![image](https://user-images.githubusercontent.com/3291391/188761756-cdd00d3f-168a-46dd-b567-b7032bed5270.png)

**Comment by Manwe-777** [comment]
Hello @maxinfet !

This is possible disabling auto resize on the overlay window you intend to use; after that, you should reset the overlay position so it does not overflow the screen and you can manipulate it.

![image](https://user-images.githubusercontent.com/4711391/188765325-6f5a12ce-f5da-4a9c-a6b7-9aa7fdb0ac7b.png)

After that the deck will have a scrollbar. Hope this helps!

**Comment by Manwe-777** [comment]
Closing as it was aparently resolved
