### ISSUE TITLE
"In boosters" button not working properly in "Cards View" on Collection tab

### ISSUE THREAD

**Issue by raistlinmaestre** [mtgatool/mtgatool-desktop#43]
When changing the button from "All cards" to "In boosters" they all dissapear and if you deselect and select again the set, all cards from the set (including ones _not_ in boosters) will show again as if "All cards" was selected instead.

Default:
![photo_2022-10-10_21-02-55](https://user-images.githubusercontent.com/9573397/194935608-ba3e29d4-4fde-4775-abef-747a8387cc16.jpg)

Changing to "In boosters":
![photo_2022-10-10_21-02-58](https://user-images.githubusercontent.com/9573397/194935684-fbd7def8-7683-4b95-8724-b9b2ad8838dd.jpg)

Deselecting the set:
![photo_2022-10-10_21-03-00](https://user-images.githubusercontent.com/9573397/194935949-20277707-5306-4f75-a269-c6b241b1179e.jpg)

Selecting it again:
![photo_2022-10-10_21-03-05](https://user-images.githubusercontent.com/9573397/194936004-27fa2e75-2d31-478f-bddb-85d1aae13c8e.jpg)

If you change it to "Not in boosters", the behaviour is the same: when you change it from the default ("All cards") to "Not in boosters" it shows nothing, then deselect and select again the set and all cards are shown instead of only the ones not in boosters.

Version 6.2.3 tested on Linux Mint 19.2

**Comment by Manwe-777** [comment]
Should be fixed for the latest `dev` (current web version/next desktop release)
