### ISSUE TITLE
peer connection errors

### ISSUE THREAD

**Issue by Dunkhan** [mtgatool/mtgatool-desktop#47]
Linux Desktop

On the release client:
Deck stats do not update after games
After a few minutes the windows goes black and can no longer be interacted with.

On the debugger:
Deck stats do not update after games
After a few minutes the application displays an error message:

Unhandled Rejection (Error): cannot send after peer is destroyed
Peer.send
node_modules/simple-peer/index.js:248
(anonymous function)
src/toolDbNetwork.ts:194
  191 |  * Clean the announce offers pool
  192 |  */
  193 | _this.cleanPool = function () {
\> 194 |     Object.entries(_this.offerPool).forEach(function (_a) {
   195 |         var id = _a[0], peer = _a[1].peer;
  196 |         if (!_this.handledOffers[id] && !_this._connectedPeers[id]) {
  197 |             // this.tooldb.logger("closed peer " + id);

if this message is closed another appears shortly after.
After about half an hour the error message changes to one about being unable to create new peer connections due to limit being reached.

I don't know how any of this part of the code works or I would try to tackle this myself.

**Comment by Manwe-777** [comment]
This one should be fixed in the latest updates

**Comment by Dunkhan** [comment]
Thanks for sorting this out, works great now
