### ISSUE TITLE
Collection downloaded as CSV bug

### ISSUE THREAD

**Issue by Arkewas** [mtgatool/mtgatool-desktop#52]
As already reported at  ⁠#support-bugs channel on Discord this feature doesn't work as it should. As you can see from the attached screenshots the owned cards are 27160. I have downloaded my collection as a CSV file, including digital sets, and on CSV file the sum of all cards is 26765 so 395 cards are missing.
I think this is a important feature as with a CSV file it's possible to import MTG Arena collection to specific MTG websites like Moxfield or Deckstats for example but with that lot of missing cards is completely useless.
I hope the developer/s will be able to fix it.
![Collection](https://github.com/mtgatool/mtgatool-desktop/assets/85570370/544d24c8-e1e7-4abf-bf3c-70be6163ea7e)
![Collection CSV](https://github.com/mtgatool/mtgatool-desktop/assets/85570370/d4ddbd59-54d8-4096-8ca2-d9645b1c3769)

**Comment by Manwe-777** [comment]
Hello!

Bear in mind the code that counts in the UI as "owned cards" counts every card object in the database, that includes tokens and some other objects that arent really cards, unlike the export feature (for example wildcards have entries, dungeons, emblems, etc dont show in the exported csv)

This indicator is mostly for connection/db sanity check, It could work like that but it might be off when you dont export digital/unowned for example..

**Comment by Arkewas** [comment]
Hi,
thank you for the fast reply but I still think something is still wrong. For example I have in collection 4 copies of "Arctic Treeline" as it shown in Collection tab but in CSV file there is no trace of them. Also another user posted the same CSV at https://discord.com/channels/463844727654187020/467737642306371584/1093255071451586690

**Comment by Arkewas** [comment]
He reported the same CSV bug so the exporting process doesn't work for all cards anyway.

**Comment by Manwe-777** [comment]
Can you make sure the cards you own are the latest in the app? for example; open a booster and note the amount of one of those cards you own after the booster is opened, then check that in mtgatool's collection view to make sure the latest data is there, sometimes the daemon does not have the latest data in it and you might have to restart mtgatool for it to fetch it.

If it does have the latest data in, then we can inspect deeper, something might be off with the export

**Comment by Arkewas** [comment]
I'm sure of this and the Collection tab works fine, the recent acquired cards are marked with yellow diamonds. Also I collected that Kaldheim lands a lot of time ago.

**Comment by Manwe-777** [comment]
Interesting, yeah those lands have the same rarity as a basic land, thats easy to fix.

Is there any other cards (nonlands) you noticed missing?

**Comment by Arkewas** [comment]
Yes, the same issue occurs, i.e. for the following Dominaria United non-basic common lands Sacred Peaks, Haunted Mire, Wooded Ridgeline, Idyllic Beachfront, Sunlit Marsh, Contaminated Aquifer, Geothermal Bog, Molten Tributary: they are shown in MTG Arena Tool collection tab but are missing in CSV file. Oddly the Dominaria United non-basic common land Crystal Grotto is shown in collection and it's also present in CSV file.

**Comment by Arkewas** [comment]
For non lands missing cards I still have to  check. I'll keep you informed.

**Comment by Manwe-777** [comment]
Merging f86dc90db902cdb34b9e24fef15528490fc133c2 to master, that cotains the lands export fix

**Comment by riQQ** [comment]
Fixed in version [6.2.10](https://github.com/mtgatool/mtgatool-desktop/releases/tag/v6.2.10).
