### ISSUE TITLE
Running but not updating

### ISSUE THREAD

**Issue by danielfreire-dev** [mtgatool/mtgatool-desktop#54]
Hi, I can get MTG Arena Tool running, but it doesn't update on Linux.
`{"isRunning":"true", "daemonVersion":"1.0.6.1", "updating":"false", "processId":20020}`

MTG Arena: Steam Client
Distro: Tumbleweed

**Comment by riQQ** [comment]
The version you're seeing is [*MTGA tracker daemon*](https://github.com/frcaton/mtga-tracker-daemon)'s version. 1.0.6.1 is the current version, therefore there's no update. *MTGA tracker daemon* is used by *mtgatool* to read information that is only available on *MTGA*'s memory and not in the logs.
