### ISSUE TITLE
Can no longer aggregate Historic Brawl data

### ISSUE THREAD

**Issue by SabreCat** [mtgatool/mtgatool-desktop#55]
Historic Brawl is the main format I play on Arena, so for a while I did my part to gather data for it by running the aggregator on the event type. Sometime within the last week or so, though, it's stopped working--I go to Explore > "try the aggregator", open the event type dropdown, and scroll to the bottom to click "Other Events", but the submenu never unfolds and the additional events including Brawl Historic never show up.
![image](https://github.com/mtgatool/mtgatool-desktop/assets/4501321/899845c2-b7a8-452c-9d7f-b1f658f301c5)

**Comment by riQQ** [comment]
Can confirm that it doesn't work with v6.1.2.

**Comment by Manwe-777** [comment]
6.3.3 still has aggregation issues, toolDb is missing some helpers to make the explore data aggregations on the web worker side

**Comment by riQQ** [comment]
Still broken with 6.3.10

**Comment by riQQ** [comment]
Working with 6.3.11:

![Screenshot mtgatool explore Historic Brawl successful](https://github.com/mtgatool/mtgatool-desktop/assets/3404787/96f5636a-1203-4c8a-ab60-8a5baa5eec53)
