### ISSUE TITLE
Data in Different Account IDs for the same account

### ISSUE THREAD

**Issue by tosimplicity** [mtgatool/mtgatool-desktop#56]
### Description

I have more than one account. Let's say account A and B. After I change account from A to B then back to A, new data will appear under a new account ID, as shown in image below. So, even I play in the same account A, data can't be seen under the same account ID.
![Screenshot_20230705160837186](https://i2.100024.xyz/2023/07/05/qm76j6.webp)

### Expected

After switching account back and forth, data of the same account can stay together. 
Using real account name like MyName#73943 might be better than arena application internal account ID.

### Version

V6.2.11

**Comment by Manwe-777** [comment]
Duplicate of #62
