### ISSUE TITLE
Problem with "Card Winrates" in version 6.0.13

### ISSUE THREAD

**Issue by marintoro** [mtgatool/mtgatool-desktop#6]
Hello, I think there is an issue with the tab "Card Winrates". When I click on it I have a empty screen even though the tracker got the data (he gives me my stats Victory-Defeat with the right opponent). This was working on version 5.X.
There is 2 screenshot one showing exactly the tab "Card Winrates" I am talking about and the second one is the empty screen I got after clicking.
![problem_with_card_winrate](https://user-images.githubusercontent.com/10373813/138366153-bc94a445-8fd9-4381-8710-5b5e160253e7.png)

![empty_card_winrate](https://user-images.githubusercontent.com/10373813/138366142-3159051c-8fc2-4c6c-98da-216526b4e752.png)

**Comment by riQQ** [comment]
Works for me 6.1.28.
Please reopen, if it isn't fixed for you. Then it likely is a more specific bug.
