### ISSUE TITLE
Match history is lost after updating to 6.3.1

### ISSUE THREAD

**Issue by azkore** [mtgatool/mtgatool-desktop#61]
I had more than 1000 matches in the history with 6.2.13, after updating to 6.3.1 only 64 is left, all of them from more than a month ago for some reason. Downgrading to 6.2.13 restores the history. Is there any way to keep the history with the new version?

**Comment by Manwe-777** [comment]
Closing in favor of #62 , same issue with this side effect

**Comment by azkore** [comment]
This was closed as a duplciate of #62, but #62 is now fixed and my match history is still empty with 6.3.8. I downgraded to 6.2.13 to get the correct history. Should I create a new issue with the same description?
