### ISSUE TITLE
App switches between AccountId and UserId when game starts

### ISSUE THREAD

**Issue by zyll71** [mtgatool/mtgatool-desktop#62]
**Observed behavior:**

When the app version 6.3.2 starts just after opening MTG Arena, is finds the PlayerSocialID and uses it as the AccountId. 

`cat Player.log | grep SocialId`

`[UnityCrossThreadLogger]==> LogBusinessEvents {"id":"bcea865d-4801-46fa-9842-a764c5b149b4","request":"{\"Type\":1912,\"TransId\":\"bcea865d-4801-46fa-9842-a764c5b149b4\",\"Payload\":\"{\\\"PlayerSocialId\\\":\\\"C4BVIKBIAVD5TAMUCJMHU3LAEY\\\",\\\"PlayersOnFriendsListOnline\\\":0,\\\"PlayersOnFriendsListTotal\\\":0,\\\"EventType\\\":44,\\\"EventTime\\\":\\\"2023-09-18T10:48:23.329347Z\\\"}\"}"}`
`[UnityCrossThreadLogger]==> LogBusinessEvents {"id":"6ea47d28-adae-46c1-b075-98ae14259d10","request":"{\"Type\":1912,\"TransId\":\"6ea47d28-adae-46c1-b075-98ae14259d10\",\"Payload\":\"{\\\"PlayerSocialId\\\":\\\"C4BVIKBIAVD5TAMUCJMHU3LAEY\\\",\\\"NewStatus\\\":\\\"Available\\\",\\\"OldStatus\\\":\\\"Offline\\\",\\\"SceneId\\\":\\\"MainNavigation\\\",\\\"Validity\\\":\\\"Verified\\\",\\\"EventType\\\":37,\\\"EventTime\\\":\\\"2023-09-18T10:48:23.3317155Z\\\"}\"}"}`

This value is not provided as the actual AccountId at this time.

`cat Player.log | grep AccountId`
`[UnityCrossThreadLogger]==> LogBusinessEvents {"id":"56b002cc-f31c-4292-b0b7-234f001a6225","request":"{\"Type\":1912,\"TransId\":\"56b002cc-f31c-4292-b0b7-234f001a6225\",\"Payload\":\"{\\\"EventName\\\":\\\"ClientStartup\\\",\\\"Data\\\":{\\\"BuildVersion\\\":\\\"2023.29.10.4670\\\",\\\"RegionId\\\":\\\"USA\\\",\\\"InstallId\\\":\\\"NoInstallID-909c48e7-d16f-44b7-b8de-52227853d44e\\\",\\\"PersonaId\\\":\\\"NoInstallID-909c48e7-d16f-44b7-b8de-52227853d44e\\\",\\\"AccountId\\\":\\\"NoInstallID-909c48e7-d16f-44b7-b8de-52227853d44e\\\",\\\"ClientPlatform\\\":\\\"SteamWindows\\\",\\\"AppSessionId\\\":\\\"fbafa2d8-7320-4036-8f3a-ef8eb065a2f9\\\"},\\\"EventType\\\":72,\\\"EventTime\\\":\\\"2023-09-18T10:48:05.4349399Z\\\"}\"}"}`
`[UnityCrossThreadLogger]==> LogBusinessEvents {"id":"3b8b0c0a-f6f0-481a-90f4-1c96a5e7c849","request":"{\"Type\":1912,\"TransId\":\"3b8b0c0a-f6f0-481a-90f4-1c96a5e7c849\",\"Payload\":\"{\\\"EventName\\\":\\\"AttemptLogin\\\",\\\"Data\\\":{\\\"Action\\\":\\\"Automatic\\\",\\\"Type\\\":\\\"credential\\\",\\\"RegionId\\\":\\\"USA\\\",\\\"InstallId\\\":\\\"NoInstallID-909c48e7-d16f-44b7-b8de-52227853d44e\\\",\\\"PersonaId\\\":\\\"NoInstallID-909c48e7-d16f-44b7-b8de-52227853d44e\\\",\\\"AccountId\\\":\\\"NoInstallID-909c48e7-d16f-44b7-b8de-52227853d44e\\\",\\\"ClientPlatform\\\":\\\"SteamWindows\\\",\\\"AppSessionId\\\":\\\"fbafa2d8-7320-4036-8f3a-ef8eb065a2f9\\\"},\\\"EventType\\\":72,\\\"EventTime\\\":\\\"2023-09-18T10:48:06.3928175Z\\\"}\"}"}`

The app selects the PlayerSocialId as the AccountId.

![image](https://github.com/mtgatool/mtgatool-desktop/assets/59997333/0305945f-daeb-45df-96cd-6ed6db8966a1)

Side note: Current ranking in MTG Arena differs from the ranking displayed in the app

![image](https://github.com/mtgatool/mtgatool-desktop/assets/59997333/5b9a26ba-4622-465d-a639-ff7fd152f114)

Editing decks, going to the store, etc. does not add change this usage of the PlayerSocialId as the AccountId.

Upon joining a game, the ID used by the app changes to the userId.

![image](https://github.com/mtgatool/mtgatool-desktop/assets/59997333/fbc9e838-1e87-49e1-b000-b7f92ce324ef)

`{ "transactionId": "0ce58f40-b40e-4c04-839f-0afffcbeba57", "requestId": 2, "timestamp": "1695035308359", "matchGameRoomStateChangedEvent": { "gameRoomInfo": { "gameRoomConfig": { "reservedPlayers": [ { "userId": "ZIRYF7P7M5EYDFO4GTSKWET33E", "playerName": "hemiola#14831", "systemSeatId": 1, "teamId": 1, "connectionInfo": { "connectionState": "ConnectionState_Open" }, "courseId": "Avatar_Basic_GideonJura", "sessionId": "ea653653-1054-4335-a86d-ddccfbf3d46e", "platformId": "iPhone", "eventId": "Play" }, { "userId": "OLBB3LMWIZAD5LDODAISXWG53Y", "playerName": "Zyll#59190", "systemSeatId": 2, "teamId": 2, "connectionInfo": { "connectionState": "ConnectionState_Open" }, "courseId": "Avatar_Basic_AjaniGoldmane", "sessionId": "de54c6a5-1e77-4924-82c0-9f6a7e2496ee", "platformId": "SteamWindows", "eventId": "Play" } ], "matchId": "b777b6df-ea7b-4cfa-b886-38fea12a9d5e", "greConfig": { "gameStateRedactorConfiguration": { "enableRedaction": true, "enableForceDiff": true }, "clipsConfiguration": { }, "checkpointConfiguration": { } }, "greHostLoggerLevel": "Info", "joinRoomTimeoutSecs": 60, "playerDisconnectTimeoutSecs": 30 }, "stateType": "MatchGameRoomStateType_Playing", "players": [ { "userId": "ZIRYF7P7M5EYDFO4GTSKWET33E", "systemSeatId": 1 }, { "userId": "OLBB3LMWIZAD5LDODAISXWG53Y", "systemSeatId": 2 } ] } } }`

This is the likely cause for storing the game under the key value associated with the userID. 

Side note: the rankings displayed in the app and MTG Arena match.

After returning to the MTG Arena menus, the app automatically changes the AccountId value back to the PlayerSocialId value. The logged game is not visible in the history unless one  manually switches the AccountId to the userID value, selects History, and refreshes the with sync symbol. 

This is possibly related to issue #61 

Side note: The app's displayed ranking no longer matches that shown in MTGArena.

**Expected behavior**

The Account Id remains the same so that games are logged under the same Id key value as the app displays per default.
All past games are visible in the history and are reflected in the stats. 

Ranking is correctly displayed in the app once the values are available in the log just before MTG Arena displays the main menu after launching.

**Additional Suggestion**

When introducing a fix, please provide a clean-up tool allowing the merging of the data currently stored under the alternate key int that of the key finally used.

Edit: correct log key lables.

**Comment by Manwe-777** [comment]
So looking around , accountId is not something we care about now, rather we only need the socialId, that is used during matches and everywhere else. I can probably make it query the current social ID once every a while so it stays up to date..

**Comment by zyll71** [comment]
Yeah. I can't see any value associated with the log's accountId, so that should be ignored.
I mistakenly referenced the log's PlayerSocialId as SocialId above. sorry for the confusion.
What might require additional investigation is why both the log's PlayerSocialId and accountId show up in the app's config menu as valid choices.

**Comment by MrNukealizer** [comment]
> So looking around , accountId is not something we care about now, rather we only need the socialId, that is used during matches and everywhere else. I can probably make it query the current social ID once every a while so it stays up to date..

Then why is all of my match history (especially before two IDs existed) under the AccountID rather than the SocialID? I don't see anything except constructed/limited rank connected to the SocialID, whereas everything else uses the AccountID.

**Comment by zyll71** [comment]
> Then why are all of my match history and decks (especially before two IDs existed) under the AccountID rather than the SocialID? I don't see anything except constructed/limited rank connected to the SocialID, whereas everything else uses the AccountID.

The log's AccountId seems to be empty (at least playing unranked BO1 and quick draft). Do you mean the log's userId?

**Comment by MrNukealizer** [comment]
> The log's AccountId seems to be empty (at least playing unranked BO1 and quick draft). Do you mean the log's userId?

I mean whatever ID existed before PlayerSocialId was added. A quick glance at my log shows that it it appears as userId, clientId, and in a bunch of log lines about sending or receiving events.

**Comment by zyll71** [comment]
Understood. My current PlayerSocialId does not match my current userId. Are yours identical?

On September 20, 2023 9:44:45 AM GMT+02:00, "Mr. Nukealizer" ***@***.***> wrote:
>> The log's AccountId seems to be empty (at least playing unranked BO1 and quick draft). Do you mean the log's userId?
>
>I mean whatever ID existed before PlayerSocialId was added. A quick glance at my log shows that it it appears as userId, clientId, and in a bunch of log lines about sending or receiving events.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/mtgatool/mtgatool-desktop/issues/62#issuecomment-1727149328
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by MrNukealizer** [comment]
Nope, my PlayerSocialId is different.

**Comment by Manwe-777** [comment]
Possible fix in 3bd32d94e27f4390abe1e47a47a7fd8d974b1bf1

On my end, the playerSocialId and PlayerId were the exact same, thus the confusion for me. Something is funky with my account after the change (probably some internal wotc accounts stuff we dont know about)

**Comment by zyll71** [comment]
> Possible fix in [3bd32d9](https://github.com/mtgatool/mtgatool-desktop/commit/3bd32d94e27f4390abe1e47a47a7fd8d974b1bf1) (to release in v6.3.3)

> farewell social id, long live client id 

Final question for my understanding: what led you to decide on dropping the PlayerSocialId? 
In my logs from the last couple of days the PlayerSocialId shows up right when the MTGA starts up. After clicking on all sorts MTGA's menu items, I only have seen the userId and clientId during game transactions up until now (but that is no exhaustive). That means the app would not know the Id until a game was played.

**Comment by zyll71** [comment]
6.3.3's Account ID is still flipping between the log's PlayerSocialId and the userId/clientId depending on game play. My current games seem to be saved with the latter.

**Comment by Manwe-777** [comment]
@zyll71 The playerSocialId is not the one we need, I was very confused because on my logs both are the same, but other users brought to my attention the one they were using before this change was introduced was the clientId/userid and not the socia id, that is the newer and might be different for some.

The userid/clientid can be obtained via the daemon or when a game starts, and its the one we always used for our tracking, I need to maintain the same ID so old users that now suddenly have a social id thats different can have their data under the same ID as it always been.

**Comment by riQQ** [comment]
Some users reported that [v6.3.8](https://github.com/mtgatool/mtgatool-desktop/releases/tag/v6.3.8) fixes this problem for them.
