### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by Porkepix** [mtgatool/mtgatool-desktop#7]
Is it planed to get back an offline mode for people mainly interested by their own stats/collection tracking assistant, like it used to be possible with v5 and earlier?

**Comment by Porkepix** [comment]
@Manwe-777 I might miss something, but I don't see any way to skip login or account creation and use mtgatool completely offline as it used to be possible on the v5.
Tested just now on `v6.1.35`.

**Comment by Manwe-777** [comment]
> @Manwe-777 I might miss something, but I don't see any way to skip login or account creation and use mtgatool completely offline as it used to be possible on the v5. Tested just now on `v6.1.35`.

Offline works (just tested it to make sure), the only thing that requires network, 100% of the times as of today is signup, since we need to make sure the user the alias does not conflict with other users, so it gets saved somewhere. Else you might lose your credentials entirely.

**Comment by Porkepix** [comment]
> > @Manwe-777 I might miss something, but I don't see any way to skip login or account creation and use mtgatool completely offline as it used to be possible on the v5. Tested just now on `v6.1.35`.
> 
> Offline works (just tested it to make sure), the only thing that requires network, 100% of the times as of today is signup, since we need to make sure the user the alias does not conflict with other users, so it gets saved somewhere. Else you might lose your credentials entirely.

So that doesn't solve the issue I opened back then: on the v5 I never ever created any single account. I just had mtgatool running locally and that's all.

**Comment by Porkepix** [comment]
@Manwe-777 Regarding the fact it can't be run locally, nor accountless as underlined above, can this be reopened? I can rename the issue if you want, if you feel the title wasn't precise enough?
