### ISSUE TITLE
`mtgatool.com` certificate expired

### ISSUE THREAD

**Issue by Frefreak** [mtgatool/mtgatool-desktop#83]
The cert of https://mtgatool.com had expired on Thu, 20 Jun 2024 23:59:59 GMT. As a result this seems to affect the startup process of mtgatool (I have yet to login successfully, not sure if related, probably another issue though)

**Comment by riQQ** [comment]
Even though the cert is still expire I can login nonetheless.

**Comment by Frefreak** [comment]
Indeed login is working. As for the cert it appears that my browser is fine with it now, but openssl says `unable to get local issuer certificate`. The tool works fine though.

**Comment by riQQ** [comment]
The certificate has been renewed in the meantime.
